import { Article, SourceStatus } from "@/types";

const now = Date.now();
const min = 60_000;

export const MOCK_ARTICLES: Article[] = [
  {
    id: "m1",
    title: "Federal Reserve signals potential rate cut amid slowing inflation data",
    description: "The Federal Reserve has indicated it may begin cutting interest rates in the coming months as inflation continues to cool toward its 2% target. Chair Jerome Powell emphasized a data-dependent approach while markets rally on the news.",
    link: "https://example.com/1",
    pubDate: new Date(now - 3 * min).toISOString(),
    source: "reuters",
    sourceName: "Reuters",
    category: "economy",
    isBreaking: true,
    isHot: true,
    duplicateCount: 3,
    relatedSources: ["Reuters", "BBC Business", "Financial Times"],
    aiSummary: "La Fed signale un possible assouplissement monétaire face au recul de l'inflation vers l'objectif de 2%. Les marchés réagissent positivement à la perspective de baisses de taux dans les mois à venir.",
    aiEntities: ["Federal Reserve", "Jerome Powell", "USA"],
    aiSentiment: "positive",
  },
  {
    id: "m2",
    title: "Ukraine launches major counter-offensive in eastern Donetsk region",
    description: "Ukrainian forces have begun a significant military operation along the eastern front, recapturing several villages in the Donetsk region. Western allies express cautious optimism as the offensive gains momentum.",
    link: "https://example.com/2",
    pubDate: new Date(now - 8 * min).toISOString(),
    source: "bbc-world",
    sourceName: "BBC World",
    category: "war-geo",
    isBreaking: true,
    isHot: true,
    duplicateCount: 4,
    relatedSources: ["BBC World", "Al Jazeera", "Reuters", "NYT World"],
    aiSummary: "L'Ukraine lance une contre-offensive majeure dans le Donetsk, reprenant plusieurs villages. Les alliés occidentaux observent avec un optimisme prudent la progression des forces ukrainiennes.",
    aiEntities: ["Ukraine", "Donetsk", "OTAN"],
    aiSentiment: "alarming",
  },
  {
    id: "m3",
    title: "European markets surge on ECB stimulus expectations",
    description: "Major European indices posted their strongest gains in months as investors bet on additional stimulus measures from the European Central Bank. The DAX rose 2.3% while the CAC 40 gained 1.8%.",
    link: "https://example.com/3",
    pubDate: new Date(now - 15 * min).toISOString(),
    source: "ft",
    sourceName: "Financial Times",
    category: "markets",
    isBreaking: false,
    isHot: true,
    duplicateCount: 2,
    relatedSources: ["Financial Times", "Guardian Economics"],
    aiSummary: null,
    aiEntities: [],
    aiSentiment: null,
  },
  {
    id: "m4",
    title: "China GDP growth slows to 4.2% as property crisis deepens",
    description: "China's economic growth has decelerated further in the latest quarter, falling below the government's 5% target as the property sector continues to weigh on the economy. Beijing announces new stimulus measures.",
    link: "https://example.com/4",
    pubDate: new Date(now - 25 * min).toISOString(),
    source: "guardian-economics",
    sourceName: "Guardian Economics",
    category: "economy",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m5",
    title: "Netanyahu faces growing domestic pressure over Gaza ceasefire talks",
    description: "Israeli Prime Minister Benjamin Netanyahu is under increasing pressure from coalition partners and the public as ceasefire negotiations with Hamas enter a critical phase. Mass protests continue in Tel Aviv.",
    link: "https://example.com/5",
    pubDate: new Date(now - 35 * min).toISOString(),
    source: "aljazeera",
    sourceName: "Al Jazeera",
    category: "war-geo",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m6",
    title: "UK Parliament votes on controversial immigration reform bill",
    description: "The House of Commons is debating a sweeping immigration reform bill that would overhaul the UK's asylum system. The vote is expected to be tight, with several Conservative MPs threatening to rebel.",
    link: "https://example.com/6",
    pubDate: new Date(now - 45 * min).toISOString(),
    source: "guardian-world",
    sourceName: "Guardian World",
    category: "politics",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m7",
    title: "S&P 500 hits record high as tech earnings exceed expectations",
    description: "The S&P 500 index reached a new all-time high following better-than-expected earnings from major technology companies. Apple, Microsoft, and Nvidia all posted strong quarterly results.",
    link: "https://example.com/7",
    pubDate: new Date(now - 55 * min).toISOString(),
    source: "nyt-business",
    sourceName: "NYT Business",
    category: "markets",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m8",
    title: "Massive earthquake strikes Turkey's southeastern coast, rescue efforts underway",
    description: "A 6.8 magnitude earthquake has hit southeastern Turkey, causing significant damage and casualties. International rescue teams are being mobilized as authorities declare a state of emergency.",
    link: "https://example.com/8",
    pubDate: new Date(now - 62 * min).toISOString(),
    source: "bbc-world",
    sourceName: "BBC World",
    category: "world",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m9",
    title: "French election polls show far-right gaining momentum ahead of snap vote",
    description: "Latest polling data shows Marine Le Pen's party consolidating its lead ahead of the snap parliamentary elections called by President Macron. Analysts warn of a potential political earthquake.",
    link: "https://example.com/9",
    pubDate: new Date(now - 78 * min).toISOString(),
    source: "guardian-world",
    sourceName: "Guardian World",
    category: "politics",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m10",
    title: "OPEC+ agrees to extend oil production cuts through Q3",
    description: "OPEC and its allies have agreed to maintain current oil production cuts through the third quarter, defying pressure from major consuming nations to increase output. Oil prices jump 3% on the announcement.",
    link: "https://example.com/10",
    pubDate: new Date(now - 90 * min).toISOString(),
    source: "reuters",
    sourceName: "Reuters",
    category: "markets",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m11",
    title: "India and Pakistan de-escalate border tensions after diplomatic talks",
    description: "India and Pakistan have agreed to pull back troops from disputed border areas following emergency diplomatic talks mediated by the United Nations. Both nations released statements calling for continued dialogue.",
    link: "https://example.com/11",
    pubDate: new Date(now - 105 * min).toISOString(),
    source: "aljazeera",
    sourceName: "Al Jazeera",
    category: "world",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m12",
    title: "Bitcoin breaks $80,000 barrier as institutional adoption accelerates",
    description: "Bitcoin surpassed the $80,000 mark for the first time, driven by growing institutional investment and the success of spot Bitcoin ETFs. Trading volumes hit record levels across major exchanges.",
    link: "https://example.com/12",
    pubDate: new Date(now - 120 * min).toISOString(),
    source: "ft",
    sourceName: "Financial Times",
    category: "markets",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m13",
    title: "UN Security Council deadlocked on Sudan humanitarian crisis resolution",
    description: "The UN Security Council failed to pass a resolution on the deepening humanitarian crisis in Sudan after Russia and China vetoed the proposal. Aid agencies warn of an imminent famine affecting millions.",
    link: "https://example.com/13",
    pubDate: new Date(now - 140 * min).toISOString(),
    source: "nyt-world",
    sourceName: "NYT World",
    category: "war-geo",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m14",
    title: "EU imposes new tariffs on Chinese electric vehicles amid trade war fears",
    description: "The European Union has announced tariffs of up to 38% on Chinese electric vehicle imports, escalating trade tensions between the two major economic blocs. Beijing threatens retaliatory measures.",
    link: "https://example.com/14",
    pubDate: new Date(now - 160 * min).toISOString(),
    source: "bbc-business",
    sourceName: "BBC Business",
    category: "economy",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m15",
    title: "Trump leads Biden in six key swing states according to new polling",
    description: "A comprehensive poll across six battleground states shows former President Trump leading President Biden by margins of 3-7 points. The economy and immigration remain top voter concerns.",
    link: "https://example.com/15",
    pubDate: new Date(now - 180 * min).toISOString(),
    source: "nyt-world",
    sourceName: "NYT World",
    category: "politics",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m16",
    title: "German industrial output falls for fourth consecutive month",
    description: "Germany's industrial production declined 1.2% in the latest month, marking the fourth straight month of contraction. The data raises fresh concerns about Europe's largest economy sliding into recession.",
    link: "https://example.com/16",
    pubDate: new Date(now - 200 * min).toISOString(),
    source: "guardian-economics",
    sourceName: "Guardian Economics",
    category: "economy",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m17",
    title: "Taiwan reports largest Chinese military incursion near its airspace",
    description: "Taiwan's defense ministry detected a record 71 Chinese military aircraft operating near the island, the largest single-day incursion on record. The US State Department urged restraint from all parties.",
    link: "https://example.com/17",
    pubDate: new Date(now - 230 * min).toISOString(),
    source: "reuters",
    sourceName: "Reuters",
    category: "war-geo",
    isBreaking: false,
    isHot: true,
  },
  {
    id: "m18",
    title: "Global food prices hit two-year high amid supply chain disruptions",
    description: "The FAO Food Price Index reached its highest level in two years, driven by rising grain and dairy prices. Climate-related disruptions and the ongoing conflict in Ukraine continue to strain global supply chains.",
    link: "https://example.com/18",
    pubDate: new Date(now - 260 * min).toISOString(),
    source: "bbc-business",
    sourceName: "BBC Business",
    category: "economy",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m19",
    title: "Iran nuclear talks collapse as Tehran enriches uranium to 84%",
    description: "Diplomatic efforts to revive the Iran nuclear deal have collapsed after IAEA inspectors confirmed Iran is enriching uranium to near weapons-grade levels of 84%. Western nations threaten new sanctions.",
    link: "https://example.com/19",
    pubDate: new Date(now - 290 * min).toISOString(),
    source: "aljazeera",
    sourceName: "Al Jazeera",
    category: "world",
    isBreaking: false,
    isHot: false,
  },
  {
    id: "m20",
    title: "Nvidia overtakes Apple as world's most valuable company",
    description: "Nvidia's market capitalization surpassed Apple's for the first time, making it the world's most valuable publicly traded company. The chipmaker's dominance in AI hardware continues to drive unprecedented growth.",
    link: "https://example.com/20",
    pubDate: new Date(now - 320 * min).toISOString(),
    source: "ft",
    sourceName: "Financial Times",
    category: "markets",
    isBreaking: false,
    isHot: true,
  },
];

export const MOCK_SOURCES: SourceStatus[] = [
  { id: "bbc-world", name: "BBC World", online: true, articleCount: 24, lastFetch: new Date().toISOString() },
  { id: "bbc-business", name: "BBC Business", online: true, articleCount: 18, lastFetch: new Date().toISOString() },
  { id: "guardian-world", name: "Guardian World", online: true, articleCount: 22, lastFetch: new Date().toISOString() },
  { id: "guardian-economics", name: "Guardian Economics", online: true, articleCount: 12, lastFetch: new Date().toISOString() },
  { id: "aljazeera", name: "Al Jazeera", online: true, articleCount: 30, lastFetch: new Date().toISOString() },
  { id: "reuters", name: "Reuters", online: true, articleCount: 28, lastFetch: new Date().toISOString() },
  { id: "nyt-world", name: "NYT World", online: true, articleCount: 20, lastFetch: new Date().toISOString() },
  { id: "nyt-business", name: "NYT Business", online: true, articleCount: 15, lastFetch: new Date().toISOString() },
  { id: "ft", name: "Financial Times", online: false, articleCount: 0, lastFetch: null },
];
